# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.5"
manifest_format = "2.0"
project_hash = "55e8f89967ddea1c226fd91ad7f8d89d5385729c"

[[deps.TighterInformedBound]]
path = "."
uuid = "2afd7a37-1555-438f-a2e5-6641a1612ac9"
version = "1.0.0-DEV"
