name = "TighterInformedBound"
uuid = "2afd7a37-1555-438f-a2e5-6641a1612ac9"
authors = ["Merlijn Krale"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
